export {default as Home} from './Home'
export {default as About} from './About'
export {default as Expertise} from './Expertise'
export {default as Contact} from './Contact'
export {default as Blog} from './Blog'